services:
  postgres-compose:
    image: postgres
    container_name: postgres-dev

    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"

    volumes:
      - D:/DEV/doc-postgres:/var/lib/postgresql

    restart: unless-stopped