version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../Server/helpdesk-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/helpdesk
    depends_on:
      - postgres

  frontend:
    build: ../Client/helpdesk
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: