version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: helpdesk
      POSTGRES_USER: ${HELPDESK_DB_USER}
      POSTGRES_PASSWORD: ${HELPDESK_DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../Server/helpdesk-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/helpdesk
      DB_USER: ${HELPDESK_DB_USER}
      DB_PASSWORD: ${HELPDESK_DB_PASS}
      JWT_SECRET: ${HELPDESK_JWT_SECRET}
      APP_MAIL_ADDRESS: ${HELPDESK_MAIL_ADDRESS}
      APP_MAIL_PASS: ${HELPDESK_MAIL_PASS}
      APP_MAIL_HOST: ${HELPDESK_MAIL_HOST}
    depends_on:
      - postgres

  frontend:
    build: ../Client/helpdesk
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata: