spring.application.name=helpdesk-server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
app.mail.address=${APP_MAIL_ADDRESS}
spring.mail.host=${APP_MAIL_HOST}
spring.mail.username=${APP_MAIL_ADDRESS}
spring.mail.password=${APP_MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.port=587
jwt.expiration-ms=3600000